<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="canonical" href="https://thegoblog.github.io/go1.13-errors" />
    <link rel="apple-touch-icon" href="/go.png" />
    <link rel="stylesheet" href="/assets/css/style.css" />
    <link rel="stylesheet" href="/style.css" />
    <title>Working with Errors in Go 1.13 | The Go Blog</title>
    
  </head>

  <header>
    <div class="container-md px-3 my-5 markdown-body"></div>
  </header>

  <body>
    <div class="container-md px-3 my-5 markdown-body">
      <h1><a href="/">The Go Blog</a></h1>
      
    <h2>Working with Errors in Go 1.13</h2>
    <p class="author">
    Damien Neil and Jonathan Amsterdam<br/>
    17 October 2019
    </p>
    
  
  
    
      
  <h4 id="TOC_1.">Introduction</h4>
  <p>Go’s treatment of <a href="https://TheGoBlog.GitHub.io/errors-are-values" target="_blank" rel="noopener">errors as values</a>
has served us well over the last decade. Although the standard library’s support
for errors has been minimal—just the <code>errors.New</code> and <code>fmt.Errorf</code> functions,
which produce errors that contain only a message—the built-in <code>error</code> interface
allows Go programmers to add whatever information they desire. All it requires
is a type that implements an <code>Error</code> method:</p>
<pre><code>type QueryError struct {
    Query string
    Err   error
}

func (e *QueryError) Error() string { return e.Query + &#34;: &#34; + e.Err.Error() }
</code></pre>
<p>Error types like this one are ubiquitous, and the information they store varies
widely, from timestamps to filenames to server addresses. Often, that
information includes another, lower-level error to provide additional context.</p>
<p>The pattern of one error containing another is so pervasive in Go code that,
after <a href="https://github.com/golang/go/issues/29934" target="_blank" rel="noopener">extensive discussion</a>, Go 1.13 added
explicit support for it. This post describes the additions to the standard
library that provide that support: three new functions in the <code>errors</code> package,
and a new formatting verb for <code>fmt.Errorf</code>.</p>
<p>Before describing the changes in detail, let&#39;s review how errors are examined
and constructed in previous versions of the language.</p>


    
      
  <h4 id="TOC_2.">Errors before Go 1.13</h4>
  
  <h4 id="TOC_2.1.">Examining errors</h4>
  <p>Go errors are values. Programs make decisions based on those values in a few
ways. The most common is to compare an error to <code>nil</code> to see if an operation
failed.</p>
<pre><code>if err != nil {
    // something went wrong
}
</code></pre>
<p>Sometimes we compare an error to a known <em>sentinel</em> value, to see if a specific error has occurred.</p>
<pre><code>var ErrNotFound = errors.New(&#34;not found&#34;)

if err == ErrNotFound {
    // something wasn&#39;t found
}
</code></pre>
<p>An error value may be of any type which satisfies the language-defined <code>error</code>
interface. A program can use a type assertion or type switch to view an error
value as a more specific type.</p>
<pre><code>type NotFoundError struct {
    Name string
}

func (e *NotFoundError) Error() string { return e.Name + &#34;: not found&#34; }

if e, ok := err.(*NotFoundError); ok {
    // e.Name wasn&#39;t found
}</code></pre>


  <h4 id="TOC_2.2.">Adding information</h4>
  <p>Frequently a function passes an error up the call stack while adding information
to it, like a brief description of what was happening when the error occurred. A
simple way to do this is to construct a new error that includes the text of the
previous one:</p>
<pre><code>if err != nil {
    return fmt.Errorf(&#34;decompress %v: %v&#34;, name, err)
}
</code></pre>
<p>Creating a new error with <code>fmt.Errorf</code> discards everything from the original
error except the text. As we saw above with <code>QueryError</code>, we may sometimes want
to define a new error type that contains the underlying error, preserving it for
inspection by code. Here is <code>QueryError</code> again:</p>
<pre><code>type QueryError struct {
    Query string
    Err   error
}
</code></pre>
<p>Programs can look inside a <code>*QueryError</code> value to make decisions based on the
underlying error. You&#39;ll sometimes see this referred to as &#34;unwrapping&#34; the
error.</p>
<pre><code>if e, ok := err.(*QueryError); ok &amp;&amp; e.Err == ErrPermission {
    // query failed because of a permission problem
}
</code></pre>
<p>The <code>os.PathError</code> type in the standard library is another example of one error which contains another.</p>



    
      
  <h4 id="TOC_3.">Errors in Go 1.13</h4>
  
  <h4 id="TOC_3.1.">The Unwrap method</h4>
  <p>Go 1.13 introduces new features to the <code>errors</code> and <code>fmt</code> standard library
packages to simplify working with errors that contain other errors. The most
significant of these is a convention rather than a change: an error which
contains another may implement an <code>Unwrap</code> method returning the underlying
error. If <code>e1.Unwrap()</code> returns <code>e2</code>, then we say that <code>e1</code> <em>wraps</em> <code>e2</code>, and
that you can <em>unwrap</em> <code>e1</code> to get <code>e2</code>.</p>
<p>Following this convention, we can give the <code>QueryError</code> type above an <code>Unwrap</code>
method that returns its contained error:</p>
<pre><code>func (e *QueryError) Unwrap() error { return e.Err }
</code></pre>
<p>The result of unwrapping an error may itself have an <code>Unwrap</code> method; we call
the sequence of errors produced by repeated unwrapping the <em>error chain</em>.</p>


  <h4 id="TOC_3.2.">Examining errors with Is and As</h4>
  <p>The Go 1.13 <code>errors</code> package includes two new functions for examining errors: <code>Is</code> and <code>As</code>.</p>
<p>The <code>errors.Is</code> function compares an error to a value.</p>
<pre><code>// Similar to:
//   if err == ErrNotFound { … }
if errors.Is(err, ErrNotFound) {
    // something wasn&#39;t found
}
</code></pre>
<p>The <code>As</code> function tests whether an error is a specific type.</p>
<pre><code>// Similar to:
//   if e, ok := err.(*QueryError); ok { … }
var e *QueryError
// Note: *QueryError is the type of the error.
if errors.As(err, &amp;e) {
    // err is a *QueryError, and e is set to the error&#39;s value
}
</code></pre>
<p>In the simplest case, the <code>errors.Is</code> function behaves like a comparison to a
sentinel error, and the <code>errors.As</code> function behaves like a type assertion. When
operating on wrapped errors, however, these functions consider all the errors in
a chain. Let&#39;s look again at the example from above of unwrapping a <code>QueryError</code>
to examine the underlying error:</p>
<pre><code>if e, ok := err.(*QueryError); ok &amp;&amp; e.Err == ErrPermission {
    // query failed because of a permission problem
}
</code></pre>
<p>Using the <code>errors.Is</code> function, we can write this as:</p>
<pre><code>if errors.Is(err, ErrPermission) {
    // err, or some error that it wraps, is a permission problem
}
</code></pre>
<p>The <code>errors</code> package also includes a new <code>Unwrap</code> function which returns the
result of calling an error&#39;s <code>Unwrap</code> method, or <code>nil</code> when the error has no
<code>Unwrap</code> method. It is usually better to use <code>errors.Is</code> or <code>errors.As</code>,
however, since these functions will examine the entire chain in a single call.</p>
<p>Note: although it may feel odd to take a pointer to a pointer, in this case it
is correct. Think of it instead as taking a pointer to a value of the error
type; it so happens in this case that the returned error is a pointer type.</p>


  <h4 id="TOC_3.3.">Wrapping errors with %w</h4>
  <p>As mentioned earlier, it is common to use the <code>fmt.Errorf</code> function to add additional information to an error.</p>
<pre><code>if err != nil {
    return fmt.Errorf(&#34;decompress %v: %v&#34;, name, err)
}
</code></pre>
<p>In Go 1.13, the <code>fmt.Errorf</code> function supports a new <code>%w</code> verb. When this verb
is present, the error returned by <code>fmt.Errorf</code> will have an <code>Unwrap</code> method
returning the argument of <code>%w</code>, which must be an error. In all other ways, <code>%w</code>
is identical to <code>%v</code>.</p>
<pre><code>if err != nil {
    // Return an error which unwraps to err.
    return fmt.Errorf(&#34;decompress %v: %w&#34;, name, err)
}
</code></pre>
<p>Wrapping an error with <code>%w</code> makes it available to <code>errors.Is</code> and <code>errors.As</code>:</p>
<pre><code>err := fmt.Errorf(&#34;access denied: %w&#34;, ErrPermission)
...
if errors.Is(err, ErrPermission) ...</code></pre>


  <h4 id="TOC_3.4.">Whether to Wrap</h4>
  <p>When adding additional context to an error, either with <code>fmt.Errorf</code> or by
implementing a custom type, you need to decide whether the new error should wrap
the original. There is no single answer to this question; it depends on the
context in which the new error is created. Wrap an error to expose it to
callers. Do not wrap an error when doing so would expose implementation details.</p>
<p>As one example, imagine a <code>Parse</code> function which reads a complex data structure
from an <code>io.Reader</code>. If an error occurs, we wish to report the line and column
number at which it occurred. If the error occurs while reading from the
<code>io.Reader</code>, we will want to wrap that error to allow inspection of the
underlying problem. Since the caller provided the <code>io.Reader</code> to the function,
it makes sense to expose the error produced by it.</p>
<p>In contrast, a function which makes several calls to a database probably should
not return an error which unwraps to the result of one of those calls. If the
database used by the function is an implementation detail, then exposing these
errors is a violation of abstraction. For example, if the <code>LookupUser</code> function
of your package <code>pkg</code> uses Go&#39;s <code>database/sql</code> package, then it may encounter a
<code>sql.ErrNoRows</code> error. If you return that error with
<code>fmt.Errorf(&#34;accessing DB: %v&#34;, err)</code>
then a caller cannot look inside to find the <code>sql.ErrNoRows</code>. But if
the function instead returns <code>fmt.Errorf(&#34;accessing DB: %w&#34;, err)</code>, then a
caller could reasonably write</p>
<pre><code>err := pkg.LookupUser(...)
if errors.Is(err, sql.ErrNoRows) …
</code></pre>
<p>At that point, the function must always return <code>sql.ErrNoRows</code> if you don&#39;t want
to break your clients, even if you switch to a different database package. In
other words, wrapping an error makes that error part of your API. If you don&#39;t
want to commit to supporting that error as part of your API in the future, you
shouldn&#39;t wrap the error.</p>
<p>It’s important to remember that whether you wrap or not, the error text will be
the same. A <em>person</em> trying to understand the error will have the same information
either way; the choice to wrap is about whether to give <em>programs</em> additional
information so they can make more informed decisions, or to withhold that
information to preserve an abstraction layer.</p>



    
      
  <h4 id="TOC_4.">Customizing error tests with Is and As methods</h4>
  <p>The <code>errors.Is</code> function examines each error in a chain for a match with a
target value. By default, an error matches the target if the two are equal. In
addition, an error in the chain may declare that it matches a target by
implementing an <code>Is</code> <em>method</em>.</p>
<p>As an example, consider this error inspired by the
<a href="https://commandcenter.blogspot.com/2017/12/error-handling-in-upspin.html" target="_blank" rel="noopener">Upspin error package</a>
which compares an error against a template, considering only fields which are
non-zero in the template:</p>
<pre><code>type Error struct {
    Path string
    User string
}

func (e *Error) Is(target error) bool {
    t, ok := target.(*Error)
    if !ok {
        return false
    }
    return (e.Path == t.Path || t.Path == &#34;&#34;) &amp;&amp;
           (e.User == t.User || t.User == &#34;&#34;)
}

if errors.Is(err, &amp;Error{User: &#34;someuser&#34;}) {
    // err&#39;s User field is &#34;someuser&#34;.
}
</code></pre>
<p>The <code>errors.As</code> function similarly consults an <code>As</code> method when present.</p>


    
      
  <h4 id="TOC_5.">Errors and package APIs</h4>
  <p>A package which returns errors (and most do) should describe what properties of
those errors programmers may rely on. A well-designed package will also avoid
returning errors with properties that should not be relied upon.</p>
<p>The simplest specification is to say that operations either succeed or fail,
returning a nil or non-nil error value respectively. In many cases, no further
information is needed.</p>
<p>If we wish a function to return an identifiable error condition, such as &#34;item
not found,&#34; we might return an error wrapping a sentinel.</p>
<pre><code>var ErrNotFound = errors.New(&#34;not found&#34;)

// FetchItem returns the named item.
//
// If no item with the name exists, FetchItem returns an error
// wrapping ErrNotFound.
func FetchItem(name string) (*Item, error) {
    if itemNotFound(name) {
        return nil, fmt.Errorf(&#34;%q: %w&#34;, name, ErrNotFound)
    }
    // ...
}
</code></pre>
<p>There are other existing patterns for providing errors which can be semantically
examined by the caller, such as directly returning a sentinel value, a specific
type, or a value which can be examined with a predicate function.</p>
<p>In all cases, care should be taken not to expose internal details to the user.
As we touched on in &#34;Whether to Wrap&#34; above, when you return
an error from another package you should convert the error to a form that does
not expose the underlying error, unless you are willing to commit to returning
that specific error in the future.</p>
<pre><code>f, err := os.Open(filename)
if err != nil {
    // The *os.PathError returned by os.Open is an internal detail.
    // To avoid exposing it to the caller, repackage it as a new
    // error with the same text. We use the %v formatting verb, since
    // %w would permit the caller to unwrap the original *os.PathError.
    return fmt.Errorf(&#34;%v&#34;, err)
}
</code></pre>
<p>If a function is defined as returning an error wrapping some sentinel or type,
do not return the underlying error directly.</p>
<pre><code>var ErrPermission = errors.New(&#34;permission denied&#34;)

// DoSomething returns an error wrapping ErrPermission if the user
// does not have permission to do something.
func DoSomething() error {
    if !userHasPermission() {
        // If we return ErrPermission directly, callers might come
        // to depend on the exact error value, writing code like this:
        //
        //     if err := pkg.DoSomething(); err == pkg.ErrPermission { … }
        //
        // This will cause problems if we want to add additional
        // context to the error in the future. To avoid this, we
        // return an error wrapping the sentinel so that users must
        // always unwrap it:
        //
        //     if err := pkg.DoSomething(); errors.Is(err, pkg.ErrPermission) { ... }
        return fmt.Errorf(&#34;%w&#34;, ErrPermission)
    }
    // ...
}</code></pre>


    
      
  <h4 id="TOC_6.">Conclusion</h4>
  <p>Although the changes we’ve discussed amount to just three functions and a
formatting verb, we hope they will go a long way toward improving how errors are
handled in Go programs. We expect that wrapping to provide additional context
will become commonplace, helping programs to make better decisions and helping
programmers to find bugs more quickly.</p>
<p>As Russ Cox said in his <a href="https://TheGoBlog.GitHub.io/experiment" target="_blank" rel="noopener">GopherCon 2019 keynote</a>,
on the path to Go 2 we experiment, simplify and ship. Now that we’ve
shipped these changes, we look forward to the experiments that will follow.</p>


    
  

  
    </div>
  </body>

  <footer>
    <div class="container-md px-3 my-5 markdown-body">
      <p><br /></p>
    </div>
  </footer>
</html>
